name: Build and Push to Docker Hub

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Grant Execution Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build -x test -PartefactVersion=${{ github.event.release.tag_name }}

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg APP_VERSION="${{ github.event.release.tag_name }}"
            -t ${{ vars.DOCKERHUB_USERNAME }}/surge-converter:${{ github.event.release.tag_name }} \
            -t ${{ vars.DOCKERHUB_USERNAME }}/surge-converter:latest \
            --push .